ZEN-33033 Add endpoints for AWS modeler server
zenoss/zenoss-service pull request #687
Opened 2020-10-15 12:49 UTC by DeKapito

2020-10-15 12:55 UTC, jpeacock-zenoss reviewed
~There should be a migration script written to add this endpoint to the services.~
Premature question.  Where does this `localhost_aws_modeler_server` endpoint come from?

2020-10-15 12:55 UTC, jpeacock-zenoss commented on services/Zenoss.cse/Zenoss/Collection/localhost/localhost/zenmodeler/service.json
> +            "Application": "{{(parent .).Name}}_aws_modeler_server",
What service exports this endpoint?

2020-10-15 13:02 UTC, DeKapito commented on services/Zenoss.cse/Zenoss/Collection/localhost/localhost/zenmodeler/service.json
> +            "Application": "{{(parent .).Name}}_aws_modeler_server",
zenpython

2020-10-15 13:08 UTC, DeKapito commented on services/Zenoss.cse/Zenoss/Collection/localhost/localhost/zenmodeler/service.json
> +            "Application": "{{(parent .).Name}}_aws_modeler_server",
This pr also adds the export for zenpython service

2020-10-15 13:39 UTC, jpeacock-zenoss requested changes
Please include a service migration script to add this endpoint to the service definitions.

2020-10-19 07:39 UTC, romanbakaleyko commented
service migration script is in the zenpack https://github.com/zenoss/ZenPacks.zenoss.AWS/blob/d40f7fff0d97ff7d25f7d8d7d015cbd72d185acc/ZenPacks/zenoss/AWS/service_migration.py

2020-10-19 11:15 UTC, jpeacock-zenoss approved these changes

2020-10-19 11:16 UTC, jpeacock-zenoss commented
OK.  I see that the service definitions are updated when the AWS ZenPack is installed.  Since ZenPacks are re-installed during an upgrade, then this should take care of the migration.

2020-10-19 11:18 UTC, merged