IMP-32279: Remove zope based service deadlock healthchecks from CZ
zenoss/zenoss-service pull request #690
Opened 2020-10-19 13:56 UTC by Deer-WarLord

2020-10-19 14:54 UTC, romanbakaleyko requested changes

2020-10-19 14:54 UTC, romanbakaleyko commented on migrations/src/zenservicemigration/migrations/remove_deadlock_from_zope_based.py
> +    if len(zope_based_services) != len(svc_names):
why do we need to check services?

2020-10-19 14:58 UTC, jpeacock-zenoss commented on migrations/src/zenservicemigration/migrations/remove_deadlock_from_zope_based.py
> +    if len(zope_based_services) != len(svc_names):
I would add that the migration script should modify the services it can find, unless there's some reason why it should be a all or nothing.

2020-10-20 08:06 UTC, Deer-WarLord commented on migrations/src/zenservicemigration/migrations/remove_deadlock_from_zope_based.py
> +    if len(zope_based_services) != len(svc_names):
fixed

2020-10-20 08:07 UTC, Deer-WarLord commented on migrations/src/zenservicemigration/migrations/remove_deadlock_from_zope_based.py
> +    if service._Service__data["HealthChecks"]:
fixed

2020-10-20 08:07 UTC, Deer-WarLord commented on migrations/src/zenservicemigration/migrations/remove_deadlock_from_zope_based.py
> +    if len(zope_based_services) != len(svc_names):
fixed

2020-10-20 19:52 UTC, jpeacock-zenoss requested changes

2020-10-20 19:52 UTC, jpeacock-zenoss commented on migrations/src/zenservicemigration/migrations/remove_deadlock_from_zope_based.py
> +    service.healthChecks = [hc.name for hc in service.healthChecks if hc.name != "deadlock_check"]
Should not 
```
... = [hc.name for hc in .... ]
```
be written as
```
... = [hc for hc in ...
```
?

2020-10-21 13:26 UTC, Deer-WarLord commented on migrations/src/zenservicemigration/migrations/remove_deadlock_from_zope_based.py
> +    service.healthChecks = [hc.name for hc in service.healthChecks if hc.name != "deadlock_check"]
fixed

2020-10-21 13:29 UTC, romanbakaleyko approved these changes
please squash commits

2020-10-21 13:32 UTC, Deer-WarLord commented
> please squash commits

done

2020-10-22 14:18 UTC, jpeacock-zenoss approved these changes

2020-10-26 12:52 UTC, merged