ZEN-33016 New zenhubworker service for flexible per-customer tuning
zenoss/zenoss-service pull request #694
Opened 2020-11-19 14:01 UTC by romanbakaleyko

2020-11-19 14:32 UTC, jpeacock-zenoss requested changes

2020-11-19 14:32 UTC, jpeacock-zenoss commented on migrations/src/zenservicemigration/migrations/add_zenhubworker_user.py
> +    zh = next((s for s in ctx.services if s.name == "zenhub"), None)
While uncommon, this code should handle the situation of multiple zenhub services deployed (i.e. multiple hubs).

2020-11-19 15:31 UTC, romanbakaleyko commented on migrations/src/zenservicemigration/migrations/add_zenhubworker_user.py
> +    zh = next((s for s in ctx.services if s.name == "zenhub"), None)
fixed

2020-11-19 16:12 UTC, jpeacock-zenoss requested changes

2020-11-19 16:12 UTC, jpeacock-zenoss commented on migrations/src/zenservicemigration/migrations/add_zenhubworker_user.py
> +        print("zenhubworker (user) service succesfully added")
There are three 's' in 'successfully'.

2020-11-20 12:46 UTC, jpeacock-zenoss requested changes

2020-11-20 12:46 UTC, jpeacock-zenoss commented on services/Zenoss.cse/Zenoss/Collection/localhost/zenhub-server.yaml
> +    spec: "Products.ZenHub.server.executors:WorkerPoolExecutor"
This file is not needed.

2020-11-20 12:46 UTC, jpeacock-zenoss commented on services/Zenoss.cse/Zenoss/Collection/localhost/zenhub/service.json
> +            "FileName": "/opt/zenoss/etc/zenhubservicecall.json",
These should be `/opt/zenoss/etc/zenhub-server.yaml`.

2020-11-20 13:02 UTC, romanbakaleyko commented on services/Zenoss.cse/Zenoss/Collection/localhost/zenhub/service.json
> +            "FileName": "/opt/zenoss/etc/zenhubservicecall.json",
done

2020-11-20 13:02 UTC, romanbakaleyko commented on services/Zenoss.cse/Zenoss/Collection/localhost/zenhub-server.yaml
> +    spec: "Products.ZenHub.server.executors:WorkerPoolExecutor"
done

2020-11-20 13:07 UTC, jpeacock-zenoss requested changes

2020-11-20 13:07 UTC, jpeacock-zenoss commented on services/Zenoss.cse/Zenoss/Collection/localhost/zenhub/service.json
> +        "/opt/zenoss/etc/zenhubservicecall.conf": {
The convention has been to have the key and filename consistent with each other so this key should should also read `/opt/zenoss/etc/zenhub-server.yaml`.

2020-11-20 13:29 UTC, romanbakaleyko commented
test this

2020-11-20 13:35 UTC, romanbakaleyko commented on services/Zenoss.cse/Zenoss/Collection/localhost/zenhub/service.json
> +        "/opt/zenoss/etc/zenhubservicecall.conf": {
done

2020-11-20 13:52 UTC, jpeacock-zenoss approved these changes

2020-11-20 13:52 UTC, merged